# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-20 11:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joins', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='join',
            name='ip_adress',
            field=models.CharField(default='ABC', max_length=120),
        ),
    ]
