# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-20 12:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joins', '0002_join_ip_adress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='join',
            name='ip_adress',
            field=models.CharField(default='foo', max_length=120),
        ),
    ]
