# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-20 13:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joins', '0007_auto_20160920_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='join',
            name='email',
            field=models.EmailField(),
        ),
    ]
