# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-23 07:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joins', '0009_auto_20160920_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='join',
            name='ref_id',
            field=models.CharField(default='ABC', max_length=120),
        ),
    ]
